name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install huggingface_hub==0.17.4

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ secrets.HF_REPO }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          huggingface-cli repo create $HF_REPO --space
          huggingface-cli repo push $HF_REPO --branch main
